---
title: "index"
output: html_document
---

###load libraries
```{r}
library(raster)
library(rgdal)
library(dismo)
library(rgbif)
library(MASS)
```

### load climate/altitude rasters and state polygons
```{r}

clim.chile <- stack("rasters//clim.chile.tif")
clim.sweden <- stack("rasters//clim.sweden.tif")
clim.italy <- stack("rasters//clim.italy.tif")

# clim.colorado <- stack("rasters//clim.colorado.tif")
# clim.alaska <- stack("rasters//clim.alaska.tif")
# 
# us <- getData("GADM", country="USA", level=1) ## use state bounds from gadm website:
# alaska <- c("Alaska") ## extract states (need to uppercase everything)
# alaska = us[match(toupper(alaska),toupper(us$NAME_1)),]
# 
# colorado <- c("Colorado") ## extract states (need to uppercase everything)
# colorado = us[match(toupper(colorado),toupper(us$NAME_1)),]
```

### download species occurrences
```{r}
# 
# temp <- gbif("Silene","acaulis") ## extract species name from GBIF server
# temp<-na.omit(temp[,c("lon","lat")]) ## remove all columns except lat-long
# temp <- temp[!duplicated(temp), ] ## duplicated occurences
# temp["species.name"]<- rep(paste("Silene"," ","acaulis"),nrow(temp)) ##generate column for species name
# write.csv(temp, paste("occurrences\\","Silene.","acaulis.","occurrence.csv", sep=""),row.names=F) ##write csv with species occurences
# 
# 
# ## create bias file for Colorado
# 
# genus<- c("Mertensia","Poa","Thalictrum","Epilobium","Cerastium","Polygonum","Polemonium","Trifolium","Potentilla","Carex","Ranunculus","Arenaria","Ligusticum","Hymeneocis","Bromus","Rhodiola","Danthonia","Sedum","Abies","Achillea","Achillea","Kobresia","Eritrychum","Castilleja","Carex","Viola","Geum","Agrostis","Artemisia","Phlox","Trisetum","Taraxacum")
# species <- c("alpina","alpina","alpinum","angustifolium","beeringianum","bistortoides","brandegei","dasiphyllum","diversifolia","elynoides","eschscholtzii","fendleri","filvinum","grandiflora","inermis","integrifolia","intermedia","lanceolatum","lasiocarpa","millefolia","millefolium","myosuroides","nanum","occidentalis","pseudoscirpoidea","purpurea","rossii","scabra","scopulorum","sibirica","spicatum","vulgare")
# 
# ## download occurrences
# for(i in 1:length(genus))
# {
# key <- name_backbone(name=paste(genus[i],species[i]))$speciesKey ## extract species key from gbif
# temp <- occ_data(taxonKey = key, country="us", hasCoordinate =T)## extract species name from GBIF server
# temp <- data.frame(lon=temp$data$decimalLongitude,lat=temp$data$decimalLatitude,species.name=temp$data$name)
# temp <- temp[!duplicated(temp), ]  ## duplicated occurences
# write.csv(temp, paste("occurrences//bias.colorado//",genus[i],".",species[i], ".occurrence.csv",sep=""),row.names=F) ##write csv with species occurences
# print(i)
# }

## load occurrences files
# occurdat<-list.files("occurrences//bias.colorado//",pattern=".csv$",full=T)
# locations<-read.csv(occurdat[1])
# ## combine into one dataframe
# for(i in 2:length(occurdat)){
# temp<-read.csv(occurdat[i])
# locations<-rbind(locations,temp)
# }
# 
# ##create empty raster
# r1 <- unstack(clim.colorado)
# r1 <- r1[[1]]
# 
# ## rasterize occurrences
# occur.ras<-rasterize(locations[,1:2],r1,1)
# 
# ##crop occurrences to Colorado
# occur.states<-mask(occur.ras,r1)
# 
# ##density function to create bias raster
# presences<-which(values(occur.states)==1)
# pres.locs<-coordinates(occur.states)[presences,]
# dens<-kde2d(pres.locs[,1],pres.locs[,2],n=c(nrow(occur.states),ncol(occur.states)))
# 
# dens.ras<-raster(dens)
# 
# ## write bias file raster
# writeRaster(dens.ras, "rasters//colorado.bias.file.tif", overwrite=T)
# 

# ## create bias file for Alaska
# genus <- c("Thalictrum","Astragalus","Festuca","Astragalus","Artemisia","Salix","Poa","Potentilla","Carex","Saxifraga","Oxyria","Carex","Viola","Saxifraga","Pedicularis","Antennaria","Geum","Petasites","Stellaria","Rhododendron","Epilobium","Arnica","Luzula","Betula","Dryas","Anemone","Salix","Gentiana","Toffieldia","Salix","Saxifraga","Trisetum","Pedicularis","Cassiope","Polygonum")
# species <- c("alpinum","alpinum","altaica","arboriginorum","arctica","arctica","arctica","biflora","bigelowii","brochialis","digyna","elynoides","episula","flagellaris","flammea","friesiana","glaciale","hyperboreus","laeta","lapponicum","latifolium","lessingii","multiflora","nana","octopetala","parviflora","polaris","propinqua","pusilla","reticulata","spicata","spicatum","sudetica","tetragona","viviparum")
# 
# ## download occurrences
# for(i in 1:length(genus))
# {
# key <- name_backbone(name=paste(genus[i],species[i]))$speciesKey ## extract species key from gbif
# temp <- occ_data(taxonKey = key, country="us", hasCoordinate =T)## extract species name from GBIF server
# temp <- data.frame(lon=temp$data$decimalLongitude,lat=temp$data$decimalLatitude,species.name=temp$data$name)
# temp <- temp[!duplicated(temp), ]  ## duplicated occurences
# write.csv(temp, paste("occurrences//bias.alaska//",genus[i],".",species[i], ".occurrence.csv",sep=""),row.names=F) ##write csv with species occurences
# print(i)
# }

## load occurrences files
# occurdat<-list.files("occurrences//bias.alaska//",pattern=".csv$",full=T)
# locations<-read.csv(occurdat[1])
# ## combine into one dataframe
# for(i in 2:length(occurdat)){
# temp<-read.csv(occurdat[i])
# locations<-rbind(locations,temp)
# }
# 
# ##create empty raster
# r1 <- unstack(clim.alaska)
# r1 <- r1[[1]]
# 
# ## rasterize occurrences
# occur.ras<-rasterize(locations[,1:2],r1,1)
# 
# ##crop occurrences to Colorado
# occur.states<-mask(occur.ras,r1)
# 
# ##density function to create bias raster
# presences<-which(values(occur.states)==1)
# pres.locs<-coordinates(occur.states)[presences,]
# dens<-kde2d(pres.locs[,1],pres.locs[,2],n=c(nrow(occur.states),ncol(occur.states)))
# 
# dens.ras<-raster(dens)
# 
# ## write bias file raster
# writeRaster(dens.ras, "rasters//alaska.bias.file.tif", overwrite=T)

# 
# ## create bias file for sweden
species.list <- read.csv("species.list.csv")
species.list <- subset(species.list, gbif=="yes") ## remove species not on gbif

species.sweden <- subset(species.list, country=="Sweden")

genus <- species.sweden$subordinate.genus
species <- species.sweden$subordinate.species

## download occurrences
 for(i in 1:length(genus))
 {
 key <- name_backbone(name=paste(genus[i],species[i]))$speciesKey ## extract species key from gbif
temp <- occ_data(taxonKey = key, country="SE", hasCoordinate =T)## extract species name from GBIF server
temp <- data.frame(lon=temp$data$decimalLongitude,lat=temp$data$decimalLatitude,species.name=temp$data$name)
temp <- temp[!duplicated(temp), ]  ## duplicated occurences
write.csv(temp, paste("occurrences//bias.sweden/",genus[i],".",species[i], ".occurrence.csv",sep=""),row.names=F) ##write csv with species occurences
print(i)
}

## load occurrences files
occurdat<-list.files("occurrences//bias.sweden//",pattern=".csv$",full=T)
locations<-read.csv(occurdat[1])
## combine into one dataframe
for(i in 2:length(occurdat)){
temp<-read.csv(occurdat[i])
 locations<-rbind(locations,temp)
 }

##create empty raster
r1 <- unstack(clim.sweden)
r1 <- r1[[1]]

## rasterize occurrences
occur.ras<-rasterize(locations[,1:2],r1,1)

##crop occurrences to Colorado
occur.states<-mask(occur.ras,r1)

##density function to create bias raster
presences<-which(values(occur.states)==1)
pres.locs<-coordinates(occur.states)[presences,]
dens<-kde2d(pres.locs[,1],pres.locs[,2],n=c(nrow(occur.states),ncol(occur.states)))

dens.ras<-raster(dens)

##write bias file raster
writeRaster(dens.ras, "rasters//sweden.bias.file.tif", overwrite=T)

```

### conduct species distribution modelling
```{r}

species.area <- data.frame()

## collect species files
occurdat<-list.files("occurrences//bias.italy//",pattern=".csv$",full=T)
## climate data specification
climate <- clim.italy

for (i in 1:length(occurdat)){
## pick species name  
species.name <-basename(occurdat[i])

## species analysis of geographic extent
location <- read.csv(occurdat[i])
if(nrow(location) < 10) next  ##skip species with less than 10 occurrences
gps <- location[,1:2]
coordinates(gps) <- ~lon+lat
proj4string(gps) <- CRS("+proj=longlat +datum=WGS84")
gps <- crop(gps, extent(climate))

## create background points using areas within 1 km of occurence
set.seed(0)
samplearea <- circles(gps, d=10000, lonlat=T)
backgr <- spsample(samplearea@polygons, 1000, type='random')


## withhold 20% for sample testing
fold.p <- kfold(gps, k=5)
occtest.p <-gps[fold.p == 4, ]
occtrain.p <- gps[fold.p != 4, ]
fold.a <- kfold(backgr, k=5)
occtest.a <-backgr[fold.a == 4, ]
occtrain.a <- backgr[fold.a != 4, ]
bias.data <- raster("rasters//italy.bias.file.tif")

## maxent environment only
max1 <- maxent(climate, p=occtrain.p, a=occtrain.a, biasfile=bias.data)

eval1 <- evaluate(occtest.p, occtest.a,max1, climate)

#predict distribution
pred_me <- predict(max1, climate)

#plot(pred_me)

test <- pred_me@data@values
test[is.na(test)] <- 0
area <- mean(test)


temp <- data.frame(species=species.name, niche.area=area, AUC=eval1@auc)
species.area  <- rbind(species.area,temp)
print(i)
}

write.csv(species.area, "italy.species.values.csv")

```


```{r}
# ## silene acaulis alaska
# location <- read.csv("occurrences//Silene   acaulis  occurrence.csv")
# gps <- location[,1:2]
# coordinates(gps) <- ~lon+lat
# proj4string(gps) <- CRS("+proj=longlat +datum=WGS84")
# gps <- crop(gps, extent(clim.alaska))
# 
# 
# ## create background points using areas within 1 km of occurence
# ## Bounding box in Alaska too large, run iteratively 
# samplearea <- circles(gps[1], d=50000, lonlat=T)
# backgr <- spsample(samplearea@polygons, sample(1:5, 1), type='random')
# 
# for ( i in  2:length(gps)){
#   samplearea <- circles(gps[i], d=50000, lonlat=T)
#   test <- spsample(samplearea@polygons, sample(5, 1), type='random')
#   backgr <- rbind(backgr,test)
# }
# 
# ## withhold 20% for sample testing
# fold.p <- kfold(gps, k=5)
# occtest.p <-gps[fold.p == 4, ]
# occtrain.p <- gps[fold.p != 4, ]
# fold.a <- kfold(backgr, k=5)
# occtest.a <-backgr[fold.a == 4, ]
# occtrain.a <- backgr[fold.a != 4, ]
# bias.alaska <- raster("rasters//alaska.bias.file.tif")
# 
# ## maxent environment only
# max1 <- maxent(clim.alaska, p=occtrain.p, a=occtrain.a, biasfile=bias.alaska)
# 
# eval1 <- evaluate(occtest.p, occtest.a,max1, clim.alaska)
# 
# #predict distribution
# pred_me <- predict(max1, clim.alaska)
# 
# plot(pred_me)
```
